https://web.mit.edu/be.400/www/SVD/Singular_Value_Decomposition.htm

In [ ]:
import numpy as np
from scipy import linalg


In [ ]:
A = np.array([[2, 1],
              [0, 3]])

In [ ]:
print(A)

[[2 1]
 [0 3]]


In [ ]:
L, X = np.linalg.eig(A)

In [ ]:
print('eigenvalues: L=', L)
print('eigenvectors: X=', X)

eigenvalues: L= [2. 3.]
eigenvectors: X= [[1.         0.70710678]
 [0.         0.70710678]]


In [ ]:
B = np.array([[2, 4],
              [1, 3],
              [0, 0],
              [0, 0]])

In [ ]:
BT = B.transpose()

In [ ]:
B@BT

array([[20, 14,  0,  0],
       [14, 10,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [ ]:
L, X = np.linalg.eig(B@BT)

In [ ]:
X

array([[ 0.81741556, -0.57604844,  0.        ,  0.        ],
       [ 0.57604844,  0.81741556,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
U, S, VT = linalg.svd(B)

In [ ]:
U

array([[-0.81741556, -0.57604844,  0.        ,  0.        ],
       [-0.57604844,  0.81741556,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
print('U: ', U)
print('S: ', S)
print('VT: ', VT)

U:  [[-0.81741556 -0.57604844  0.          0.        ]
 [-0.57604844  0.81741556  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
S:  [5.4649857  0.36596619]
VT:  [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
