#Linear Algebra (Matrix)

#Matrix Operations

##Matrix Creation

In [ ]:
import numpy as np

In [ ]:
A = np.array([[1,2,3,4] ,
              [5,6,7,8] ,
              [10 , 11 , 12 ,13] ,
              [14,15,16,17]], dtype = (np.float16))
A

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [10., 11., 12., 13.],
       [14., 15., 16., 17.]], dtype=float16)

In [ ]:
print(type(A))
print(A.dtype)

<class 'numpy.ndarray'>
float16


In [ ]:
B = np.array([[1.5,2.07,3,4] , [5,6,7,8] , [10 , 11 , 12 ,13] , [14,15,16,17]])
B

array([[ 1.5 ,  2.07,  3.  ,  4.  ],
       [ 5.  ,  6.  ,  7.  ,  8.  ],
       [10.  , 11.  , 12.  , 13.  ],
       [14.  , 15.  , 16.  , 17.  ]])

In [ ]:
print(type(B))
print(B.dtype)

<class 'numpy.ndarray'>
float64


In [ ]:
A.shape

(4, 4)

In [ ]:
A[0]

array([1., 2., 3., 4.], dtype=float16)

In [ ]:
A[0][0]

1.0

In [ ]:
A[1:3]

array([[ 5.,  6.,  7.,  8.],
       [10., 11., 12., 13.]], dtype=float16)

In [ ]:
A[1:3, 1:4]

array([[ 6.,  7.,  8.],
       [11., 12., 13.]], dtype=float16)

##Zeros & Ones Matrix

In [ ]:
#روش اول برای تولید ماترس صفر با ابعاد دلخواه
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# روش دوم تولید ماتریس صفر
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#روش اول برای تولید ماترس یک با ابعاد دلخواه
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# روش دوم تولید ماتریس یک
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##Matrix with Random Numbers

In [ ]:
# np.random.seed(seed=42)
X = np.random.random((3,3))
X

array([[0.39211752, 0.34317802, 0.72904971],
       [0.43857224, 0.0596779 , 0.39804426],
       [0.73799541, 0.18249173, 0.17545176]])

##Identity Matrix

In [ ]:
#ماتریس همانی مرتبه دلخواه
I = np.eye(9)
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

##Diagonal Matrix

In [ ]:
D = np.diag([1,2,3,4,5,6,7,8])
D

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

##Traingular Matrices (lower & Upper triangular matrix)

In [ ]:
M = np.random.randn(5,5)
U = np.triu(M)
L = np.tril(M)
print("Matrix - \n" , M)
print("\n")
print("lower triangular matrix - \n" , L)
print("\n")
print("Upper triangular matrix - \n" , U)

Matrix - 
 [[-1.72766949 -0.39089979  0.57380586  0.33858905 -0.01183049]
 [ 2.39236527  0.41291216  0.97873601  2.23814334 -1.29408532]
 [-1.03878821  1.74371223 -0.79806274  0.02968323  1.06931597]
 [ 0.89070639  1.75488618  1.49564414  1.06939267 -0.77270871]
 [ 0.79486267  0.31427199 -1.32626546  1.41729905  0.80723653]]


lower triangular matrix - 
 [[-1.72766949  0.          0.          0.          0.        ]
 [ 2.39236527  0.41291216  0.          0.          0.        ]
 [-1.03878821  1.74371223 -0.79806274  0.          0.        ]
 [ 0.89070639  1.75488618  1.49564414  1.06939267  0.        ]
 [ 0.79486267  0.31427199 -1.32626546  1.41729905  0.80723653]]


Upper triangular matrix - 
 [[-1.72766949 -0.39089979  0.57380586  0.33858905 -0.01183049]
 [ 0.          0.41291216  0.97873601  2.23814334 -1.29408532]
 [ 0.          0.         -0.79806274  0.02968323  1.06931597]
 [ 0.          0.          0.          1.06939267 -0.77270871]
 [ 0.          0.          0.          0.    

##Concatenate Matrices

In [ ]:
A = np.array([[1,2] , [3,4] ,[5,6]])
B = np.array([[1,1] , [1,1]])
C = np.concatenate((A,B))
C , C.shape , type(C) , C.dtype

(array([[1, 2],
        [3, 4],
        [5, 6],
        [1, 1],
        [1, 1]]), (5, 2), numpy.ndarray, dtype('int64'))

In [ ]:
M = np.full((3,2) , 8)
print(M)
print(M.shape)

[[8 8]
 [8 8]
 [8 8]]
(3, 2)


In [ ]:
M = M.flatten()
print(M)
print(M.shape)

[8 8 8 8 8 8]
(6,)


##Matrix Addition

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)
C = M+N
print("\n Matrix Addition (M+N)  ==>  \n", C)
# OR
C = np.add(M,N,dtype = np.float64)
print("\n Matrix Addition using np.add  ==>  \n", C)


 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Addition (M+N)  ==>  
 [[ 2  3  4]
 [ 6 -1  8]
 [10 11  3]]

 Matrix Addition using np.add  ==>  
 [[ 2.  3.  4.]
 [ 6. -1.  8.]
 [10. 11.  3.]]


##Matrix subtraction

In [ ]:
#********************************************************#
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)
C = M-N
print("\n Matrix Subtraction (M-N)  ==>  \n", C)
# OR
C = np.subtract(M,N,dtype = np.float64)
print("\n Matrix Subtraction using np.subtract  ==>  \n", C)
#********************************************************#


 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Subtraction (M-N)  ==>  
 [[ 0  1  2]
 [ 2 -5  4]
 [ 4  5 -3]]

 Matrix Subtraction using np.subtract  ==>  
 [[ 0.  1.  2.]
 [ 2. -5.  4.]
 [ 4.  5. -3.]]


##Matrices Scalar Multiplication

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
C = 10
print("\n Matrix (M)  ==>  \n", M)
print("\nMatrices Scalar Multiplication ==>  \n", C*M)
# OR
print("\nMatrices Scalar Multiplication ==>  \n", np.multiply(C,M))


 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Matrices Scalar Multiplication ==>  
 [[ 10  20  30]
 [ 40 -30  60]
 [ 70  80   0]]

Matrices Scalar Multiplication ==>  
 [[ 10  20  30]
 [ 40 -30  60]
 [ 70  80   0]]


##Transpose of a matrix

In [ ]:
M = np.array([[1,2,3],[4,-3,6]])
print("\n Matrix (M)  ==>  \n", M)
print("\nTranspose of M ==>  \n", np.transpose(M))
# OR
print("\nTranspose of M ==>  \n", M.T)


 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]]

Transpose of M ==>  
 [[ 1  4]
 [ 2 -3]
 [ 3  6]]

Transpose of M ==>  
 [[ 1  4]
 [ 2 -3]
 [ 3  6]]


##Determinant of a matrix

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M)  ==>  \n", M)
print("\nDeterminant of M ==>  ", np.linalg.det(M))


 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Determinant of M ==>   195.0


##Rank of a matrix

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M)  ==>  \n", M)
print("\nRank of M ==> ", np.linalg.matrix_rank(M))


 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Rank of M ==>  3


##Trace of matrix

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M)  ==>  \n", M)
print("\nTrace of M ==> ", np.trace(M))


 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Trace of M ==>  -2


##Inverse of matrix A

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
print("\n Matrix (M)  ==>  \n", M)
print("\nInverse of M ==> \n", np.linalg.inv(M))


 Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

Inverse of M ==> 
 [[-0.24615385  0.12307692  0.10769231]
 [ 0.21538462 -0.10769231  0.03076923]
 [ 0.27179487  0.03076923 -0.05641026]]


##Matrix Multiplication (pointwise multiplication)

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)
print("\n Point-Wise Multiplication of M & N  ==> \n", M*N)
# OR
print("\n Point-Wise Multiplication of M & N  ==> \n", np.multiply(M,N))


 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Point-Wise Multiplication of M & N  ==> 
 [[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]

 Point-Wise Multiplication of M & N  ==> 
 [[ 1  2  3]
 [ 8 -6 12]
 [21 24  0]]


##Matrix dot product

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)
print("\n Matrix Dot Product ==> \n", M@N)
# OR
print("\n Matrix Dot Product using np.matmul ==> \n", np.matmul(M,N))
# OR
print("\n Matrix Dot Product using np.dot ==> \n", np.dot(M,N))


 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Dot Product ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]

 Matrix Dot Product using np.matmul ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]

 Matrix Dot Product using np.dot ==> 
 [[14 14 14]
 [16 16 16]
 [23 23 23]]


##Matrix Division

In [ ]:
M = np.array([[1,2,3],[4,-3,6],[7,8,0]])
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n First Matrix (M)  ==>  \n", M)
print("\n Second Matrix (N)  ==>  \n", N)
print("\n Matrix Division (M/N)   ==> \n", M/N)
# OR
print("\n Matrix Division (M/N)   ==> \n", np.divide(M,N))


 First Matrix (M)  ==>  
 [[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]

 Second Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]

 Matrix Division (M/N)   ==> 
 [[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]

 Matrix Division (M/N)   ==> 
 [[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]


##Sum of all elements in a matrix

In [ ]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n Matrix (N)  ==>  \n", N)
print ("Sum of all elements in a Matrix  ==>")
print (np.sum(N))


 Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Sum of all elements in a Matrix  ==>
18


##Column-Wise Addition

In [ ]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n Matrix (N)  ==>  \n", N)
print ("Column-Wise summation ==> ")
print (np.sum(N,axis=0))


 Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Column-Wise summation ==> 
[6 6 6]


##Row-Wise Addition

In [ ]:
N = np.array([[1,1,1],[2,2,2],[3,3,3]])
print("\n Matrix (N)  ==>  \n", N)
print ("Row-Wise summation  ==>")
print (np.sum(N,axis=1))


 Matrix (N)  ==>  
 [[1 1 1]
 [2 2 2]
 [3 3 3]]
Row-Wise summation  ==>
[3 6 9]


##Matrix Vector Multiplication

In [ ]:
A = np.array([[1,2,3] ,[4,5,6]])
v = np.array([10,20,30])
print ("Matrix Vector Multiplication  ==> \n" , A*v)

Matrix Vector Multiplication  ==> 
 [[ 10  40  90]
 [ 40 100 180]]


In [ ]:
A = np.array([[1,2,3] ,[4,5,6]])
v = np.array([10,20,30])
print ("Matrix Vector Multiplication  ==> \n" , A@v)

Matrix Vector Multiplication  ==> 
 [140 320]


#Tensor

In [ ]:
# Create Tensor
T1 = np.array([
  [[1,2,3],    [4,5,6],    [7,8,9]],
  [[10,20,30], [40,50,60], [70,80,90]],
  [[100,200,300], [400,500,600], [700,800,900]],
  ])
T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

#Solving Equations $AX = B$



In [ ]:
A = np.array([[1,2,3] , [4,5,6] , [7,8,8]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

In [ ]:
B = np.random.random((3,1))
B

array([[0.01612921],
       [0.59443188],
       [0.55678519]])

In [ ]:
X = np.dot(np.linalg.inv(A) , B)
X

array([[ 0.98535527],
       [-1.40853707],
       [ 0.61594936]])

In [ ]:
X = np.matmul(np.linalg.inv(A) , B)
X

array([[ 0.98535527],
       [-1.40853707],
       [ 0.61594936]])