# 🔥 Assignment: Exploring PyTorch

<p align="center">📢⚠️📂  </p>

<p align="center"> Please name your file using the format: <code>assignmentName_nickname.py/.ipynb</code> (e.g., <code>project1_ali.py</code>) and push it to GitHub with a clear commit message.</p>

<p align="center"> 🚨📝🧠 </p>

------------------------------------------------



## 🎯 Goal
This assignment evaluates your basic skills in using PyTorch, focusing on tensors, autograd, and a small training loop.



### 1️⃣ Setup and Basics
**Task:**

* Install PyTorch and check its version.

* Create a 2D tensor and print it.

In [1]:
import torch

print(torch.__version__)
x = torch.tensor([[1. , 2.] , [3. , 4.]])
print(f"x : {x}")

2.7.1+cu128
x : tensor([[1., 2.],
        [3., 4.]])


In [2]:
# Your turn:
# Create another tensor y of the same shape with values [[5, 6], [7, 8]].

y = torch.tensor([[5. , 6.] , [7. , 8.]])
print(f"y : {y}")

y : tensor([[5., 6.],
        [7., 8.]])


### 2️⃣ Tensor Operations 🧮
**Task:** Perform addition and matrix multiplication.

In [3]:
z = x + y
print("Addition:\n", z)

mat_mul = x @ y
print("Matrix Multiplication:\n", mat_mul)

Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])
Matrix Multiplication:
 tensor([[19., 22.],
        [43., 50.]])


In [4]:
# Your turn:
# Perform element-wise multiplication (x * y) and print the result.

multiplication = x * y
print(f"multiplication : {multiplication}")

multiplication : tensor([[ 5., 12.],
        [21., 32.]])


### 3️⃣ Autograd and Gradients ⚙️
**Task:** Enable gradient tracking and compute derivatives.

In [6]:
a = torch.tensor(3.0, requires_grad=True)
b = (a ** 2) + 2 * a + 1
b.backward()
print("Gradient of b wrt a:", a.grad)


Gradient of b wrt a: tensor(8.)


In [7]:
# Your turn:
# Create a tensor p with value 2.0 (requires_grad=True) and compute the gradient of q = p^3 + 4p.

p = torch.tensor(2.0 , requires_grad=True)
q = p **3 + 4 * p
q.backward()
print("Gradient of q wrt p:", p.grad)

Gradient of q wrt p: tensor(16.)


### 4️⃣ Random Tensors 🎲
**Task:** Generate a random tensor of shape (2, 3) and find its max and min.

In [8]:
rand_tensor = torch.rand((2, 3))
print("Random Tensor:\n", rand_tensor)
print("Max:", torch.max(rand_tensor))
print("Min:", torch.min(rand_tensor))


Random Tensor:
 tensor([[0.6975, 0.7858, 0.7772],
        [0.3042, 0.1020, 0.1182]])
Max: tensor(0.7858)
Min: tensor(0.1020)


### 5️⃣ Mini Training Loop 🤖
**Task:** Train a simple linear model y = wx + b using gradient descent.

In [9]:
# Data
x_train = torch.tensor([[1.0], [2.0], [3.0]])
y_train = torch.tensor([[2.0], [4.0], [6.0]])

# Model
w = torch.randn(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

# Training
learning_rate = 0.01
for epoch in range(100):
    y_pred = w * x_train + b
    loss = torch.mean((y_pred - y_train) ** 2)
    loss.backward()

    # Update
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()

print("Trained weight:", w.item())
print("Trained bias:", b.item())


Trained weight: 1.651038408279419
Trained bias: 0.793222963809967


### 6️⃣ Bonus ⚡
* Convert a PyTorch tensor to a NumPy array.

* Convert it back to a PyTorch tensor.

In [10]:
# To do

sample_1 = torch.tensor([1. , 2. , 3.])
numpy_arr = sample_1.numpy()
pytorch_tensor = torch.from_numpy(numpy_arr)

print(f"Sample 1 : {sample_1}")
print("---------------")
print(f"numpy_arr : {numpy_arr}")
print(f"Type of numpy_arr ===> {type(numpy_arr)}")
print("---------------")
print(f"pytorch_tensor : {pytorch_tensor}")
print(f"Type of pytorch_tensor ===> {type(pytorch_tensor)}")


Sample 1 : tensor([1., 2., 3.])
---------------
numpy_arr : [1. 2. 3.]
Type of numpy_arr ===> <class 'numpy.ndarray'>
---------------
pytorch_tensor : tensor([1., 2., 3.])
Type of pytorch_tensor ===> <class 'torch.Tensor'>
