# 1️⃣ Setup and Basics
Task:

Install TensorFlow and verify the version.
Create a simple tensor and print it.

In [5]:
import tensorflow as tf

print(f"Tensorflow version : {tf.__version__}")
a = tf.constant([[1,2] , [3,4]])
print(f"Tensor a : \n{a}")

Tensorflow version : 2.18.0
Tensor a : 
[[1 2]
 [3 4]]


In [9]:
b = tf.constant([[5,6] , [7,8]])
print(f"Tensor b : \n {b}")
print("--------------------")
print(f"b shape : {b.shape}")

Tensor b : 
 [[5 6]
 [7 8]]
--------------------
b shape : (2, 2)


# 2️⃣ Tensor Operations
Task: Perform element-wise addition and multiplication.

In [7]:
c = a + b
print("Addition:\n", c)

d = a * b
print("Multiplication:\n", d)


Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [10]:
multiplication = a @ b
print("Multiplication:\n", multiplication)

Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


# 3️⃣ Random Tensors 🎲
Task: Generate a random tensor of shape (3, 3) from a normal distribution and print its mean and standard deviation.

In [12]:
# Example snippet
random_tensor = tf.random.normal([3, 3])
print("Random Tensor:\n", random_tensor)
print("Mean:", tf.reduce_mean(random_tensor))
print("Std Dev:", tf.math.reduce_std(random_tensor))


Random Tensor:
 tf.Tensor(
[[ 0.5897852  -0.45510045  0.13046674]
 [-0.57042843  1.2452071   0.38936564]
 [-0.18235067 -1.5178325   0.63837725]], shape=(3, 3), dtype=float32)
Mean: tf.Tensor(0.029721094, shape=(), dtype=float32)
Std Dev: tf.Tensor(0.77000445, shape=(), dtype=float32)


# 4️⃣ Building a Simple Model 🤖
Task: Build a single-layer neural network using tf.keras.Sequential.

In [25]:
from keras.layers import Dense , Input
from keras.models import Sequential

model = Sequential()
model.add(Input(shape=(1,)))
model.add(Dense(1 , activation="relu"))
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [27]:
model_second = Sequential()
model_second.add(Input(shape=(1,)))
model_second.add(Dense(5 , activation="relu"))
model_second.add(Dense(1 , activation="relu"))
model_second.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 5)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 16 (64.00 B)

 Trainable params: 16 (64.00 B)

 Non-trainable params: 0 (0.00 B)

# 5️⃣ Bonus ⚡
Create a tensor with values from 0 to 9 (inclusive).

Reshape it to shape (2, 5).

Pint the reshaped tensor.

In [31]:
my_tensor = tf.range(10)
reshaped_tensor = tf.reshape(my_tensor ,(2,5))
print(f"reshaped Tensor : \n {reshaped_tensor}")
print("-----------------------------")
print(f"shape of reshaped Tensor : {reshaped_tensor.shape}")

reshaped Tensor : 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
-----------------------------
shape of reshaped Tensor : (2, 5)
