# 🧠 Assignment: Getting Started with TensorFlow


<p align="center">📢⚠️📂  </p>

<p align="center"> Please name your file using the format: <code>assignmentName_nickname.py/.ipynb</code> (e.g., <code>project1_ali.py</code>) and push it to GitHub with a clear commit message.</p>

<p align="center"> 🚨📝🧠 </p>

------------------------------------------------



## 🎯 Goal
This assignment evaluates your basic skills in using TensorFlow, including creating tensors, performing operations, and building a simple model.

### 1️⃣ Setup and Basics
**Task:**

* Install TensorFlow and verify the version.
* Create a simple tensor and print it.

In [8]:
# Example snippet
import tensorflow as tf

print("TensorFlow version:", tf.__version__)
a = tf.constant([[1, 2], [3, 4]])
print("Tensor a:\n", a)


TensorFlow version: 2.20.0
Tensor a:
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [9]:
# Your turn:
# Create a tensor b with values [[5, 6], [7, 8]] and print its shape.
b = tf.constant([[5, 6], [7, 8]])
print("Tensor b:\n", b)



Tensor b:
 tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


### 2️⃣ Tensor Operations
**Task:** Perform element-wise addition and multiplication.

In [10]:
# Example snippet
c = a + b
print("Addition:\n", c)

d = a * b
print("Multiplication:\n", d)


Addition:
 tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
Multiplication:
 tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [ ]:
# Your turn:
# Compute a @ b (matrix multiplication) and print the result.

e = a @ b
print("Matrix Multiplication:\n", e)




Matrix Multiplication:
 tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


### 3️⃣ Random Tensors 🎲
**Task:** Generate a random tensor of shape (3, 3) from a normal distribution and print its mean and standard deviation.

In [ ]:
# Example snippet

random_tensor = tf.random.normal([3, 3])
print("Random Tensor:\n", random_tensor)
print("Mean:", tf.reduce_mean(random_tensor))
print("Std Dev:", tf.math.reduce_std(random_tensor))


Random Tensor:
 tf.Tensor(
[[ 0.06132538 -0.4524595   0.00465713]
 [-0.9531849  -0.41993755  0.21351114]
 [ 0.3521335  -1.6075189  -0.04839648]], shape=(3, 3), dtype=float32)
Mean: tf.Tensor(-0.31665224, shape=(), dtype=float32)
Std Dev: tf.Tensor(0.59132975, shape=(), dtype=float32)


### 4️⃣ Building a Simple Model 🤖
**Task:** Build a single-layer neural network using tf.keras.Sequential.

In [ ]:
# Example snippet
# model = tf.keras.Sequential([
#     tf.keras.layers.Dense(1, input_shape=(1,))
# ])

model = tf.keras.Sequential([
    tf.keras.Input(shape=(1,)),
    tf.keras.layers.Dense(1)
])
model.summary()


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Your turn:
# Add another dense layer with 5 neurons and relu activation.
model = tf.keras.Sequential([
    tf.keras.Input(shape=(1,)),
    tf.keras.layers.Dense(5, activation='relu'),  # New layer with 5 neurons and relu
    tf.keras.layers.Dense(1)
])

model.summary()




Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 5)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             6 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 16 (64.00 B)

 Trainable params: 16 (64.00 B)

 Non-trainable params: 0 (0.00 B)

### 5️⃣ Bonus ⚡
* Create a tensor with values from 0 to 9 (inclusive).

* Reshape it to shape (2, 5).

* Pint the reshaped tensor.

In [ ]:
# To do
x = tf.range(10)
x_reshaped = tf.reshape(x, (2, 5))
print("Re-shaped tensor:\n", x_reshaped)





Re-shaped tensor:
 tf.Tensor(
[[0 1 2 3 4]
 [5 6 7 8 9]], shape=(2, 5), dtype=int32)
